- config/DOI_IAD2_reserved_template_20200205-mustache.xml
- config/DOI_template_20200407-mustache.xml
- input/DOI_Release_20200727_from_draft.xml
- input/DOI_Release_20200727_from_reserve.xml
- pds_doi_core/input/pds4_util.py
- pds_doi_core/outputs/osti_web_parser.py
- pds_doi_core/util/doi_validator.py
- pds_doi_core/util/emailer.py
- pds_doi_core/util/test/doi_validator_test.py
Pull request to close two issues #55 and #58:
https://github.com/NASA-PDS/pds-doi-service/issues/55 Update default DOI metadata according to changes in requirements
https://github.com/NASA-PDS/pds-doi-service/issues/58 create full_name when first/last name cannot be parsed
All the unit tests can be ran with the following commands.  Some test data are already in git and some are external URL resources.   They all are referred in the unit tests.
If the test is successful, the number of tests ran and 'OK' on the last line of output:
python3 pds_doi_core/actions/test/draft_test.py
python3 pds_doi_core/actions/test/list_test.py
python3 pds_doi_core/actions/test/check_test.py
python3 pds_doi_core/actions/test/reserve_test.py
python3 …
> Update templates for 'reserve' and 'draft'

- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/api/models/doi_record.py
- pds_doi_service/api/models/doi_summary.py
- pds_doi_service/api/swagger/swagger.yaml
- pds_doi_service/api/test/data/draft_osti_record.xml
- pds_doi_service/api/test/data/error_osti_record.xml
- pds_doi_service/api/test/data/output.xml
- pds_doi_service/api/test/data/release_osti_record.xml
- pds_doi_service/api/test/data/reserve_osti_record.xml
- pds_doi_service/api/test/test_dois_controller.py
- pds_doi_service/api/util.py
- pds_doi_service/core/actions/check.py
- pds_doi_service/core/actions/release.py
- pds_doi_service/core/input/exceptions.py
- pds_doi_service/core/outputs/osti_web_client.py
- pds_doi_service/core/outputs/osti_web_parser.py
- pds_doi_service/core/util/doi_validator.py
- pds_doi_service/core/util/initialize_production_deployment.py
**Summary**
This PR adds an implementation for the release POST endpoint of the DOI Service API. The release endpoint expects an LID or LIDVID corresponding to the existing draft or reserve record to release. The LID is used to obtain the OSTI label associated with the original request (via the list action), and this is submitted to the release action and result is returned.
Unit tests have been added for the new release endpoint. Additionally, tests have been reworked to utilize `unittest.mock.patch` for stubbing out the calls to the core action classes.
[test_results.txt](https://github.com/NASA-PDS/pds-doi-service/files/5520770/test_results.txt)
#113 #106 #79
> DOI Service API Release Endpoint

- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/api/models/doi_record.py
- pds_doi_service/api/models/doi_summary.py
- pds_doi_service/api/swagger/swagger.yaml
- pds_doi_service/api/test/test_dois_controller.py
- pds_doi_service/core/actions/list.py
- pds_doi_service/core/db/doi_database.py
**Summary**
This PR rolls up a number of fixes to how dates (datetime objects) are handled, both when provided to the DOI service, as well as when they are returned to a user. This includes:
* Updating the `DoiRecord` and `DoiSummary` class to include a `node` field, and moving the `creation_date` field out of `DoiSummary`
* Updating the core service `list` action to parse start/end time filters as iso8601 strings, as well as return `update_date` as an iso8601 string
* Fixing a time-zone related bug in the API unit tests
Unit tests have been updated where necessary to account for the new `node` field and iso8601 time strings.
[test_results.txt](https://github.com/NASA-PDS/pds-doi-service/files/5662495/test_results.txt)
Fixes #126, #127, and …
> DOI Record Date Management

- docs/source/installation/index.rst
- pds_doi_service/core/util/config_parser.py
- pds_doi_service/core/util/test/config_parser_test.py
**Summary***
The bug was that sqllite database and transaction directory were created whereever the command line tool was lauching from.
I adding a function to transform to absolute path any property finishing with _file or _dir in the configuration. 
A new unit test has been created for that.
Attached to bug #122
> transform relative path in config in absolute path based on sys.prefix

- input/DOI_Release_20200727_from_review.xml
- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/api/swagger/swagger.yaml
- pds_doi_service/api/test/test_dois_controller.py
- pds_doi_service/core/actions/draft.py
- pds_doi_service/core/actions/list.py
- pds_doi_service/core/actions/release.py
- pds_doi_service/core/actions/test/draft_test.py
- pds_doi_service/core/actions/test/release_test.py
- pds_doi_service/core/cmd/pds_doi_cmd.py
- pds_doi_service/core/outputs/DOI_IAD2_reserved_template_20200205-mustache.xml
- pds_doi_service/core/outputs/DOI_template_20200407-mustache.xml
- pds_doi_service/core/outputs/osti.py
- pds_doi_service/core/outputs/osti_web_parser.py
**Summary**
This PR adds a new "submit" endpoint to the DOI API for moving a record from draft/reserve to "review" status. The previous "release" endpoint has been (temporarily) removed to ensure Engineering Node has final say over release of a DOI. To move a record back to draft from review, a `--lidvid` option has been added to the Draft action to reset the workflow status associated to a LIDVID back to draft/pending.
This branch also rolls up a number of bug fixes, code refactors and cleanup which were deemed necessary during the development of the above features.
Unit tests have been added for the new submit endpoint, as well as to ensure that the release endpoint is no longer reachable by the API. A number of existing unit tests for the reserve endpoint …
> DOI API Submit Endpoint/--lidvid option for Draft Action

- pds_doi_service/api/__main__.py
- pds_doi_service/api/test/__init__.py
- pds_doi_service/api/test/test_dois_controller.py
**Summary***
This PR updates the initialization of the Flask/Connexion app used in the DOI API to set the "strict_slashes" flag to False.
This allows endpoints such as `/dois` and `/dois/` to resolve to the same place.
Updated unit test for /dois endpoint to ensure that using a trailing slash also works.
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/5914896/test.txt)
Reference related issues here and use `Fixes` or `Resolves` for closing issues:
#141
> Endpoint Strict Slash Checking Disable

- input/DOI_Release_20200727_from_draft.xml
- input/DOI_Release_20200727_from_reserve.xml
- input/DOI_Release_20200727_from_review.xml
- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/core/actions/draft.py
- pds_doi_service/core/actions/release.py
- pds_doi_service/core/actions/reserve.py
- pds_doi_service/core/actions/test/draft_test.py
- pds_doi_service/core/actions/test/release_test.py
- pds_doi_service/core/actions/test/reserve_test.py
- pds_doi_service/core/input/exceptions.py
- pds_doi_service/core/input/input_util.py
- pds_doi_service/core/input/pds4_util.py
- pds_doi_service/core/input/test/input_util_test.py
- pds_doi_service/core/outputs/osti.py
- pds_doi_service/core/outputs/osti_web_parser.py
- pds_doi_service/core/util/doi_validator.py
**Summary**
This PR adds support for the Draft action to consume an input OSTI XML label, either local or remote, as an alternative to PDS4 bundles. To accomplish this, the `input_util.DOIInputUtil` class has been overhauled to serve as the central location for all methods related to reading input files. A new method `parse_dois_from_input_file()` has been added that takes a file path that may correspond to a local file/directory, or remote URL. The method determines the appropriate way to parse the input based on the provide path and file extension. Additionally, a `DOIInputUtil` object can be configured with a subset of valid extensions so we can still restrict input types for different actions.
Lastly, this PR also rolls up several misc. bug fixes and improvements that were discovered …
> Draft Action Support for OSTI Label Input

- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/api/swagger/swagger.yaml
- pds_doi_service/api/test/test_dois_controller.py
- pds_doi_service/core/actions/list.py
- pds_doi_service/core/actions/test/list_test.py
**Summary**
This PR adds the ability to filter results retrieved by the List action by workflow status (draft, review, etc...). The logic to include status in a database query was actually already present, but never exposed as a command-line option. Such an option (`-status`/`--status`) has now been added. Additionally, status has been added as parameter to the DOI API GET dois endpoint.
Unit tests have been added for using the status option, both with the core draft action as well as the API.
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/5967950/test.txt)
#144
> List Action Filter by Status

- pds_doi_service/core/actions/release.py
- pds_doi_service/core/actions/reserve.py
- pds_doi_service/core/entities/doi.py
- pds_doi_service/core/outputs/DOI_IAD2_template_20200205-mustache.xml
- pds_doi_service/core/util/doi_validator.py
**Summary**
This branch contains a fix for issue #154, where the XML label returned from a submission to OSTI (such as occurs in the reserve/release actions) was in a format that would not pass validation against their own schema. The XML returned is now reformatted using the same mustache template we use to create submission labels. Additionally, there have been several fixes to the template itself and the validation calls to ensure the XML returned from OSTI submissions is usable for later workflow actions.
No unit tests have been affected by this PR
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/6030941/test.txt)
#154
> Return valid xml from OSTI submission calls

- pds_doi_service/core/input/exceptions.py
- pds_doi_service/core/outputs/osti_web_client.py
**Summary**
This PR adds checks to requests made to the OSTI server, catching any `HTTPError`s (returned from the requests library) and wrapping them with a new local exception type (`OSTIRequestException`).
Here are some sample uses of the exception when using the DOI API:
Bad URL:
```json
{
"errors": [
{
"message": "DOI submission request to OSTI service failed, reason: 500 Server Error:  for url: https://www.osti.gov/iad2test/api/fecords",
"name": "OSTIRequestException"
}
]
}
```
Bad credentials:
```json
{
"errors": [
{
"message": "DOI submission request to OSTI service failed, reason: 401 Client Error:  for url: https://www.osti.gov/iad2test/api/records",
"name": "OSTIRequestException"
}
]
}
```
No unit tests have been updated by this PR. …
> OSTI request failure exception handling

- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/api/swagger/swagger.yaml
**Summary**
With the addition of JSON support for output labels, the API could return an output label in JSON format for the GET /dois/{lidvid} endpoint. This broke consumers of the response, who always expected XML. This PR updates the API controller to always return the output label in XML format.
Additionally, the swagger.yaml definition of the API has been updated to include correct examples of the 200 responses for the POST /dois and GET /dois/{lidvid} endpoints.
No unit tests modified or added by this PR.
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/6111577/test.txt)
#159
> XML Label format for GET /dois/{lidvid} endpoint

- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/core/actions/draft.py
- pds_doi_service/core/actions/release.py
- pds_doi_service/core/actions/reserve.py
- pds_doi_service/core/actions/test/draft_test.py
- pds_doi_service/core/input/exceptions.py
- pds_doi_service/core/input/input_util.py
- pds_doi_service/core/input/pds4_util.py
**Summary***
This PR updates the handling of parsing errors for invalid PDS4/OSTI input labels such that the error details are properly propagated to the API for display back to a client. Additionally, this branch fixes a bug where such errors were returned with code 500 instead of 400.
Unit tests have been updated where necessary to accommodate new error handling fixes
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/6111630/test.txt)
#157
> Fix XML Parsing Errors Reported by API

- pds_doi_service/api/swagger/swagger.yaml
- pds_doi_service/core/actions/list.py
- pds_doi_service/core/db/doi_database.py
- pds_doi_service/core/db/test/doi_database_test.py
**Summary**
This PR updates the DOI service to allow users to provide Unix-style wildcards to LID's or LIDVID's when querying the local transaction database, either via the API or using the pds-doi-cmd CLI.
There has also been some cleanup of logging statements for the affected modules.
A unit test for querying LID/LIDVID using wildcards has been added.
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/6251195/test.txt)
- resolves #177
> LIDVID Query Wildcard Support

- pds_doi_service/api/controllers/dois_controller.py
- pds_doi_service/api/models/doi_record.py
- pds_doi_service/api/models/doi_summary.py
- pds_doi_service/api/swagger/swagger.yaml
- pds_doi_service/api/test/test_dois_controller.py
**Summary**
Simple update to the `DoiRecord` and `DoiSummary` objects to include DOI title as a field returned to the API user:
Unit tests for API controller have been updated to check for new title field.
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/6345394/test.txt)
Resolves #183
<!--
Reference related issues here and use `Fixes` or `Resolves` in order to automatically close the issue upon merge. For more information on autolinking to tickets see https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls.
* for issues in this repo:
- fixes #1
- fixes #2
- refs #3
* for issues in other repos: NASA-PDS/my_repo#1, NASA-PDS/her_repo#2
->
> Title field for DoiRecord and DoiSummary

- pds_doi_service/core/entities/doi.py
- pds_doi_service/core/outputs/osti_web_parser.py
- pds_doi_service/core/outputs/transaction.py
- pds_doi_service/core/outputs/transaction_builder.py
- pds_doi_service/core/util/general_util.py
- pds_doi_service/core/util/initialize_production_deployment.py
**Summary***
I updated the script which reads data from OSTI to populate the local sqllite database.
It now also updates the transaction_history directory.
This required updates in the transaction object to handle ids which are not lidvids.
Run:
python ./pds_doi_service/core/util/initialize_production_deployment.py -i https://www.osti.gov/iad2/api/records -s loubrieu@jpl.nasa.gov -d prod.db
- fixes: #189
> Prepare prod db

- pds_doi_service/core/outputs/osti_web_parser.py
- pds_doi_service/core/util/initialize_production_deployment.py
**Summary**
This branch overhauls the `initialize_production_deployment.py` script, so that it may be used to import existing DOI entries from OSTI to a local transaction database for use with the DOI service. There are also some minor fixes to handling of identifiers assigned to PDS3 label entries, such that they work correctly with the DOI Service API.
While testing import of the existing entries from OSTI, it was observed that the identifier fields for several entries contained extraneous whitespace, and that several PDS3 id's contained forward slashes (/), which interfere with the API routing performed for the GET /dois/{lidvid} endpoint. LIDVIDs (or any identifier) parsed from labels are now tidied up to remove any extra whitespace, as well as replace any forward slashes with …
> API Support for Legacy PDS3 DOIs

- input/DOI_Release_20210216_from_draft.json
- input/DOI_Release_20210216_from_reserve.json
- src/pds_doi_service/core/actions/test/release_test.py
- src/pds_doi_service/core/actions/test/reserve_test.py
- src/pds_doi_service/core/outputs/DOI_IAD2_template_20200205-mustache.xml
- src/pds_doi_service/core/outputs/osti.py
**Summary**
This PR fixes an issue where attempting to update the list of authors for a reserved or registered DOI entry via JSON format label would cause XML schema validation errors. A small adjustment has been made to the XML mustache template to output a valid XML label (used for validation only) even when there are no authors specified. A similar fix has been made when providing a JSON label with no contributors (editors or data curator).
Unit test suites for the reserve and release actions have been updated to cover JSON input label cases. Test data has also been modified to cover the no-authors/no-contributors cases.
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/6618734/test.txt)
Additionally, the acceptance criteria listed here …
> OSTI JSON Label Update Fix

- src/pds_doi_service/api/controllers/dois_controller.py
- src/pds_doi_service/core/actions/release.py
- src/pds_doi_service/core/actions/reserve.py
- src/pds_doi_service/core/actions/test/draft_test.py
- src/pds_doi_service/core/actions/test/list_test.py
- src/pds_doi_service/core/actions/test/release_test.py
- src/pds_doi_service/core/actions/test/reserve_test.py
- src/pds_doi_service/core/outputs/datacite/DOI_DataCite_template_20210520-jinja2.json
- src/pds_doi_service/core/outputs/datacite/datacite_record.py
- src/pds_doi_service/core/outputs/datacite/datacite_web_parser.py
- src/pds_doi_service/core/outputs/doi_record.py
- src/pds_doi_service/core/outputs/osti/DOI_IAD2_template_20210216-mustache.json
- src/pds_doi_service/core/outputs/osti/osti_record.py
**Summary** 
During the initial addition of the DataCite functionality, the interface to record rendering classes (in outputs/doi_record.py) was updated to only create an output record for a single `Doi` object at a time. This had the unexpected consequence of disrupting the workflow for the command-line tool, where it was expected to output a parsable record after each transaction.
This PR reverts the usage of the DOIRecord class and its inheritors to accept multiple `Doi` objects and render them in a single output label, which can then be saved off and resubmitted later as a valid OSTI/DataCite format input.
Regression tests have been updated where necessary to account for changes to the rendering of the output record. …
> Output Label Format Fix

- src/pds_doi_service/core/outputs/datacite/DOI_DataCite_template_20210520-jinja2.json
- src/pds_doi_service/core/outputs/datacite/datacite_record.py
- src/pds_doi_service/core/outputs/datacite/datacite_web_parser.py
- src/pds_doi_service/core/outputs/test/datacite_test.py
**Summary**
This PR addresses the ability to update DOI metadata once a record has been submitted to DataCite. Much of the required functionality was already available from previous commits, so this branch merely address a corner case where a record in the "findable" state must be moved back to "registered" via the "hide" event before it is updated.
The branch also adds some niceties to the formatting of the Jinja2 template and fixes a potential parsing error for DataCite records.
**EDIT**: Added a commit to remove support for the DataCite "registered" state, since we determined that the "draft" state was sufficient for the PDS DOI workflow
Unit tests have been updated to account for changes to the DataCite template …
> DataCite Metadata Update

- src/pds_doi_service/api/__main__.py
- src/pds_doi_service/api/test/_base.py
- src/pds_doi_service/api/test/test_dois_controller.py
- src/pds_doi_service/core/input/input_util.py
- src/pds_doi_service/core/util/conf.ini.default
**Summary**
This PR enhances the DOI API application to filter all incoming requests based on the setting of the referrer header field.
There is now a `api_valid_referrers` field in the INI config:
This field may be set to a comma-delimited list of host names that we'll allow requests from if said hostname appears in the URL of the request's referrer field. Setting the field to an empty string will disable the referrer check.
In the main module for the DOI API, all incoming requests are now checked to ensure the referrer field contains one of the valid host names. If there is a mismatch, or no referrer is specified at all, the request is denied and an HTTP error code is returned with the response:
Note that this has an unfortunate side-effect of hampering support for the built-in Swagger …
> DOI API Referrer Check

- src/pds_doi_service/api/__main__.py
- src/pds_doi_service/api/controllers/dois_controller.py
- src/pds_doi_service/api/models/doi_record.py
- src/pds_doi_service/api/models/doi_summary.py
- src/pds_doi_service/api/swagger/swagger.yaml
- src/pds_doi_service/api/test/test_dois_controller.py
**Summary**
This PR integrates the swagger definition for v0.2 of the DOI API into the controller code. v0.2 of the API was created to deal with the use `lidvid` as a path parameter to certain endpoints. Since certain lidvids could contain forward slashes, the corresponding endpoints would be unreachable. In the new spec, the `lidvid` token (now called simply called `identifier`) is included in the query section of the path, side-stepping the issue entirely.
This PR makes the necessary changes for the API controller (and associated regression tests) to meet the new spec. No new functionality has been added. Updates to bring the DOI service core library in-line with these changes will occur in a future PR. …
> DOI API v0.2 Update

- src/pds_doi_service/core/actions/draft.py
- src/pds_doi_service/core/actions/release.py
- src/pds_doi_service/core/actions/reserve.py
- src/pds_doi_service/core/input/input_util.py
- src/pds_doi_service/core/outputs/datacite/DOI_DataCite_template_20210520-jinja2.json
- src/pds_doi_service/core/outputs/datacite/__init__.py
- src/pds_doi_service/core/outputs/datacite/datacite_4.3_schema.json
- src/pds_doi_service/core/outputs/datacite/datacite_validator.py
- src/pds_doi_service/core/outputs/osti/__init__.py
- src/pds_doi_service/core/outputs/osti/osti_validator.py
- src/pds_doi_service/core/outputs/service_validator.py
- src/pds_doi_service/core/outputs/test/datacite_test.py
- src/pds_doi_service/core/util/conf.ini.default
**Summary**
This PR adds to the PDS DOI service the capability to validate DataCite-format JSON labels against their JSON schema prior to submission. This feature is required to have parity with the feature set currently available for OSTI.
Unit tests have been added for the new validation capability
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/7034542/test.txt)
Resolves #236 
<!--
Reference related issues here and use `Fixes` or `Resolves` in order to automatically close the issue upon merge. For more information on autolinking to tickets see https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls.
* for issues in this repo:
- fixes #1
- fixes #2
- refs #3
* for issues in other repos: …
> DataCite Label Validator

- src/pds_doi_service/core/actions/release.py
- src/pds_doi_service/core/actions/reserve.py
- src/pds_doi_service/core/entities/doi.py
- src/pds_doi_service/core/outputs/datacite/DOI_DataCite_template_20210520-jinja2.json
- src/pds_doi_service/core/outputs/datacite/datacite_record.py
- src/pds_doi_service/core/outputs/datacite/datacite_web_client.py
- src/pds_doi_service/core/outputs/datacite/datacite_web_parser.py
- src/pds_doi_service/core/outputs/doi_validator.py
- src/pds_doi_service/core/outputs/service.py
- src/pds_doi_service/core/outputs/test/datacite_test.py
- src/pds_doi_service/core/outputs/web_parser.py
- src/pds_doi_service/core/util/general_util.py
- src/pds_doi_service/core/util/initialize_production_deployment.py
**Summary**
This PR adds the necessary updates to be able to use the `initialize_production_deployment.py` script with both OSTI and DataCite when syncing existing DOI records to a local transaction database.
The script now provides a `--service` flag that can be used to specify the endpoint to pull DOI records from:
```
$ python initialize_production_deployment.py --service osti
INFO __main__:main Starting DOI import to local database...
INFO __main__:perform_import_to_database Using source service provider osti
INFO __main__:perform_import_to_database Using DOI prefix 10.17189
INFO __main__:perform_import_to_database Using local database /Users/collinss/repos/pds-doi-service/venv/doi.db
DEBUG pds_doi_service.core.outputs.service:get_doi_record_service Returning instance of …
```
> DataCite Sync Script Update

- docs/source/development/index.rst
- docs/source/index.rst
- docs/source/installation/index.rst
- docs/source/usage/index.rst
This branch updates the web documentation .rst files for the pds-doi-service to be in line with its current state in release v2.0.0.
I was able to successfully compile the docs via `tox docs` (although this still seemed to run the `py39` and `lint` stages anyway 🤷 ). I was also able to confirm that the sphinx argparse directive for the command-line tool was pulled into the usage page as expected.
Sample docs can be viewed here: 
[pds-doi-service-docs-2.0.0.zip](https://github.com/NASA-PDS/pds-doi-service/files/7246720/pds-doi-service-docs-2.0.0.zip)
#253
> Web Documentation update for v2.0.0

- src/pds_doi_service/core/entities/doi.py
- src/pds_doi_service/core/input/node_util.py
- src/pds_doi_service/core/outputs/datacite/datacite_web_client.py
- src/pds_doi_service/core/outputs/datacite/datacite_web_parser.py
- src/pds_doi_service/core/outputs/test/datacite_test.py
- src/pds_doi_service/core/util/initialize_production_deployment.py
This PR adds support for DataCite's pagination scheme to the query function used to pull down existing DOI records from a DataCite server. This functionality should have been included with the original addition of DataCite support, but was overlooked.
In addition to pagination support, this branch adds several other small improvements, including:
- Addition of "Radio Science" node ID to available PDS Node ID's recognized by DOI service
- Better logging of warning messages from parsing of optional fields from a DataCite label
- Better support for determining an appropriate node ID from a parsed DataCite label when importing to the local database
One of the following should be included here:
A unit test has been added for the pagination support added to the DataCite web client. …
> DataCite Query Pagination Support

- src/pds_doi_service/core/actions/list.py
- src/pds_doi_service/core/actions/test/list_test.py
Small update to add an option to the list action that returns the results of the query as a combined JSON label. This allows a user to obtain label entries for queried DOI records directly, without the need to interact with the local transaction history store.
Updated unit tests for list action to exercise the new label format feature.
[tox.log](https://github.com/NASA-PDS/pds-doi-service/files/7471320/tox.log)
Resolves #289
> Label Format Output for List Action

- src/pds_doi_service/core/actions/release.py
- src/pds_doi_service/core/actions/reserve.py
- src/pds_doi_service/core/actions/test/release_test.py
- src/pds_doi_service/core/actions/test/reserve_test.py
- src/pds_doi_service/core/actions/test/update_test.py
- src/pds_doi_service/core/actions/update.py
- src/pds_doi_service/core/entities/doi.py
- src/pds_doi_service/core/util/general_util.py
- src/pds_doi_service/core/util/test/general_util_test.py
This PR fixes handling of the global keywords assigned within the INI config to ensure that said keywords are always included with any `Doi` object handled by the reserve, update or release actions.
Unit tests have been added for the new global keyword parsing function, and existing tests for the reserve, update and release actions have been updated to ensure global keywords are always added.
[tox.log](https://github.com/NASA-PDS/pds-doi-service/files/7508247/tox.log)
Fixes #273
> Global Keywords Handling Fix

- src/pds_doi_service/core/db/doi_database.py
- src/pds_doi_service/core/db/test/doi_database_test.py
Small update to DOI transaction database code to convert usage of `GLOB` SQLite statement to `LIKE` so wildcard searches are case-insensitive by default.
Added unit tests to existing suite to test case-insensitive wildcard search
[tox.log](https://github.com/NASA-PDS/pds-doi-service/files/7522774/tox.log)
Resolves #223
> Case-Insensitve Wildcard Matching for DB Queries

- src/pds_doi_service/core/actions/release.py
- src/pds_doi_service/core/actions/reserve.py
- src/pds_doi_service/core/actions/update.py
- src/pds_doi_service/core/db/doi_database.py
- src/pds_doi_service/core/entities/doi.py
- src/pds_doi_service/core/input/input_util.py
- src/pds_doi_service/core/outputs/test/__init__.py
- src/pds_doi_service/core/outputs/test/data/pds4_bundle.xml
- src/pds_doi_service/core/outputs/test/transaction_test.py
- src/pds_doi_service/core/outputs/transaction_builder.py
- src/pds_doi_service/core/outputs/transaction_on_disk.py
This PR addresses an issue where certain files created by the DOI service did not have group-write permissions set. This prevented users other than the installer of the service to utilize the service after a fresh install or rebuild of the transaction database. The transaction classes have been updated to ensure the correct group-write permissions are set for both the transaction database file and the transaction history store.
This PR also addresses an issue discovered where the contents of an input directory could be copied multiple times in the transaction history, one for each input label within the directory. The service now assigns the source input file to each DOI parsed to ensure only the minimum set of files are copied per-transaction.
A unit test suite has been added for the …
> Group Write Permission Fix

- docs/requirements/v2.0.1/REQUIREMENTS.md
- docs/requirements/v2.1.0/REQUIREMENTS.md
- docs/requirements/v2.1.1-dev/REQUIREMENTS.md
- docs/requirements/v2.1.2-dev/REQUIREMENTS.md
- docs/source/_static/swagger.html
- docs/source/api/index.rst
- docs/source/conf.py
- docs/source/development/index.rst
- docs/source/index.rst
- docs/source/installation/index.rst
- docs/source/usage/index.rst
- setup.cfg
- src/pds_doi_service/core/actions/action.py
- src/pds_doi_service/core/actions/list.py
This PR makes a number of additions the set of ghpages documentation bundled with the DOI service. In particular, the usage page has received a large update to include in-depth descriptions for the `pds-doi-cmd` actions, and a new API page has been added to roll up the Sphinx-generated API docs for the command-line utilities. Lastly, a static HTML render of the Swagger API has been added to document the usage for `pds-doi-api`.
No core functionality added/modified by this PR, no tests have been updated.
Resolves #201 
Resolves #202
Resolves #256 
Resolves #313
> Usage Documentation Updates

- scripts/sync_dois.sh
- src/pds_doi_service/core/outputs/datacite/datacite_web_parser.py
* Add sync_dois.sh script per #309
* Update identifier handling for NoneType identifiers #331
```
$ scripts/sync_dois.sh --prefix 10.26007
...
WARNING pds_doi_service.core.outputs.datacite.datacite_web_parser:_parse_identifiers Odd metadata. NoneType identifier in record:
...
"identifiers": [
{
"identifier": "urn:nasa:pds:dart_teleobs::1.0",
"identifierType": "PDS4 Bundle ID"
},
{
"identifier": null,
"identifierType": null
}
],
...
INFO pds_doi_service.core.util.initialize_production_deployment:main DOI import complete in 5.12 seconds.
INFO pds_doi_service.core.util.initialize_production_deployment:main Num records found: 25
INFO pds_doi_service.core.util.initialize_production_deployment:main Num records processed: 25
INFO pds_doi_service.core.util.initialize_production_deployment:main …
```
> Add sync script and update identifier handling

- src/pds_doi_service/core/outputs/doi_validator.py
- src/pds_doi_service/core/outputs/test/doi_validator_test.py
Applies minor fixes to LIDVID validation logic and related exception messages.  Adds tests for new/changed validation elements.
Unit tests pass (except linting, which failed prior to changes)
Behavioural tests unable to be run per #352 
fixes #336
> Issue 336 - DOI-service application inaccurately reports LID as being invalid

- src/constants.py
- src/pds_doi_service/core/actions/reserve.py
- src/pds_doi_service/core/actions/update.py
- src/pds_doi_service/core/util/config_parser.py
- src/pds_doi_service/core/util/general_util.py
- src/pds_doi_service/core/util/logging.py
Resolves #350 (probably - given the fact that I was able to replicate @tloubrieu-jpl's experience with a fresh development environment and the fact that the error should have affected anyone using a venv and a user-defined config, I'm gonna guess this is the cause).
The path to the user-defined config at the project/repository root was incorrectly being resolved via `sys.prefix` (which is something like `path/to/doi-service/venv` when a venv is in use), and a logging bug was hiding the fact that the user-defined config was not being found/used.
This PR also fixes the logging bug, adds some explanatory context to the 404 response returned by DataCite, and improves the articulation of some comments and symbols.
Unit tests pass (except `flake8` lint)
closes #350
> Issue #350

- README.md
- setup.cfg
- src/pds_doi_service/api/controllers/authentication.py
- src/pds_doi_service/api/test/test_dois_controller.py
- src/pds_doi_service/core/actions/roundup.py
- tox.ini
see #364
- Disables four (important) test cases which fail when run in an environment that doesn't include a jwt/cognito-populated config.
- Add a tonne of flake8 ignores
- Add a mypy type ignore for external module `jose` which does not provide type hints in the current version.
- Renames tox env `py39` to `tests`
- Fixes errors in documentation regarding running individual tox environments
Tests pass (for the first time in a while!)
fixes #362 
related to #364
> disable cognito-dependent tests and extend flake8 lint ignores

- README.md
- setup.cfg
Automatic `pandas` update resulted in failure due to too-low version of `openpyxl`.
- pins `pandas` to prevent reoccurrence
- updates `openpyxl`
- adds to doco
Passes unit tests
Closes #368
> Pin pandas and update openpyxl version

- .github/workflows/branch-cicd.yaml
to allow passing DataCite and other secrets to GitHub Action
Sets branch testing action to run in newly-instantiated `branch-integration-testing` environment, which has been set up with DataCite secrets.
Removes obsolete OSTI configuration patching step.
> set branch testing to run in environment

- src/pds_doi_service/notebooks/Bulk Record Update.ipynb
Bulk Record Update erroneously refers to the collection of Doi objects parsed from DataCite as doi_records. Given that a different class DoiRecord also exists within doi-service, and especially given the way methods/attributes are sometimes generated dynamically from strings (which breaks code insight), this is a potential source of confusion and wasted time for new users of the notebook.
This PR renames some variables and amends some documentation text.
n/a
closes #374
> fix bulk-update notebook variable naming to reflect actual contents

- README.md
- src/pds_doi_service/api/test/data/bundle_in.xml
- src/pds_doi_service/api/test/data/bundle_in_with_contributors.xml
- src/pds_doi_service/core/actions/test/data/pds4_bundle.xml
- src/pds_doi_service/core/actions/test/data/pds4_bundle_with_contributors.xml
- src/pds_doi_service/core/actions/test/data/pds4_bundle_with_doi_and_contributors.xml
- src/pds_doi_service/core/db/test/data/pds4_bundle.xml
- src/pds_doi_service/core/input/pds4_util.py
- src/pds_doi_service/core/input/test/data/pds4_bundle_with_utf-8-bom.xml
- src/pds_doi_service/core/input/test/pds4_util_test.py
- tests/end_to_end/bundle_pds4.xml
Overhauls DOIPDS4LabelUtil.get_names() and its supporting private methods.
New implementation is more rigid, but more comprehensible and well-defined.  If we want more flexibility we need to implement personal/organizational entities (like are used for authors and editors) properly as classes, rather than just `Dict`s.  I understand this conversation is ongoing between @jordanpadams and other stakeholders as of last week.
Adds support for parsing of organizational names (ie those without separators).
Formats like `F.Lastname` are no longer supported.  Supported formats (per new unit tests) are
```
[
"A. Dunn",
"Dunn, Alex",
"Dunn, A.",
"Dunn, A. E.",
"Dunn, A. E. F. G.",
"Dunn, Alexander E.",
"Dunn, Alexander E. F. G.",
"Jet Propulsion Laboratory",
"JPL",
"Google Inc.",
"Suffixed Jr., …
```
> #377 author list parse

- Jenkinsfile
This updates the Jenkins pipeline by forcibly pulling the latest images mentioned in the Docker Composition during the "build" phase.
Before the fix:
```console
$ hostname
pds-expo.jpl.nasa.gov
$ docker image ls | egrep doi-service
nasapds/pds-doi-service                         latest              05492df9eb77   9 months ago    332MB
```
After the fix:
```console
$ docker image ls | egrep doi-service
nasapds/pds-doi-service                         latest              05492df9eb77   9 months ago    332MB
```
"But wait!" you exclaim. "This isn't fixed!" Ah, but the `nasapds/pds-doi-service:latest` image truly hasn't been updated in 9 months. [See for yourself](https://hub.docker.com/layers/nasapds/pds-doi-service/latest/images/sha256-b7a7b84f81fe96f89b29393dc4e9c8c8a563fc1b0f7ed49fd4c50f852 …
> Pulls latest images during build phase in Jenkins pipeline

- .gitignore
- setup.cfg
- src/pds_doi_service/api/util.py
- src/pds_doi_service/core/actions/update.py
- src/pds_doi_service/core/input/input_util.py
- src/pds_doi_service/core/outputs/test/doi_validator_test.py
- src/pds_doi_service/core/util/config_parser.py
- src/pds_doi_service/core/util/test/contributors_util_test.py
Merge this to have the DOI service complete its Roundup. In the sandbox and with the free version of GitHub Actions, this was 45 minutes. This doesn't satisfy the acceptance criterion of 30 minutes as stipulated in #403 but we're going to give this one a pass.
See [this run in the sandbox](https://github.com/nasa-pds-engineering-node/doi-service/actions/runs/4755380635).
- #403
> Bring Roundup time to 45 minutes and enable it to complete to green

- setup.cfg
While looking at some Dependabot issues, I noticed that this package could not be installed with `pip install --editable '.[dev]'`. I also noticed a large number of [Dependency Confusion Vulnerabilities](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610).
Merge this to make it installable again with the `[dev]` extra and to close those vulnerabilities.
BEFORE:
```
INFO: pip is looking at multiple versions of pds-doi-service[dev] to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following yanked versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3
ERROR: Ignored the following versions that require a different python version: 0.5.0 Requires-Python >=3.10; 0.5.1 Requires-Python >=3.10; 0.5.2 Requires-Python >=3.10; 2.1.0 …
```
> Make this pip-installable with the dev extra again (bonus: no more Dependency Confusion Vulnerabilities)

- .pre-commit-config.yaml
- .secrets.baseline
- setup.cfg
- src/pds_doi_service/api/encoder.py
- src/pds_doi_service/api/test/test_dois_controller.py
- src/pds_doi_service/core/actions/roundup/email.py
- src/pds_doi_service/core/actions/roundup/test/base.py
- src/pds_doi_service/core/actions/roundup/test/email_test.py
- src/pds_doi_service/core/actions/roundup/test/resources/roundup_email_attachment.json
- src/pds_doi_service/core/actions/roundup/test/resources/roundup_email_body.jinja2
- src/pds_doi_service/core/outputs/test/datacite_test.py
- src/pds_doi_service/core/util/emailer.py
This branch gets the existing unit test suite for the DOI Service passing again. Failing tests that were deactivated in the CI system have been re-enabled now that they pass again.
Note: In order to repair these tests, it was necessary to roll back the version of Connexion from v3.0.0 to v2.70. Other code changes added to accommodate v3.0.0 have also been reverted.
All non-deprecated tests are[ passing in Roundup](https://github.com/NASA-PDS/doi-service/actions/runs/15494897153/job/43629144750#step:5:690). No linting issues either.
Resolves #456 
Resolves #364 
Resolves #361
> Unit Test Suite Fixes
